#!/bin/bash
#PBS -l walltime=00:01:00
#PBS -l nodes=1:ppn=1
# Example Bash Script to execute a python job on batch

# load python
module load python/3.5.1

#Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

#Run the python job from the working directory
python test.py > out.txt
