#!/bin/bash
#PBS -S /bin/bash
# Torque job script to run CFX solver in parallel on a single node 

# set default resource requirements for job 
# (4 cores on 1 node requesting 3 hours 30 minutes of runtime)
# - these can be overridden on the qsub command line  
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:01:00

#Change to directory from which job was submitted
cd $PBS_O_WORKDIR

# set number of processors to run on 
# (list of node names is in file $PBS_NODEFILE)
#nprocs=`wc -l $PBS_NODEFILE | awk '{ print $1 }'`

nodes=`cat $PBS_NODEFILE`
nodes=`echo $nodes | sed -e 's/ /,/g'`
echo $nodes | sed -e 's/ /,/g'

# load cfx module so that we find the cfxsolve command
module load cfx

cfx5solve -batch -double -def Benchmark.def  -par-dist $nodes -parallel -start-method "Platform MPI Distributed Parallel"

# The following line would start the simulation from a 
# previous results file, Benchmark_001.res
#cfx5solve -double -def Benchmark.def -initial Benchmark_001.res -part $nprocs -par-local
