#!/bin/bash -login
#PBS -S /bin/bash

# Number of processors (Iridis 4 has ppn=16 max)
#PBS -l nodes=1:ppn=np
# walltime hh:mm:ss (Iridis 4 allows for 60:00:00)
#PBS -l walltime=00:10:00
# job name
#PBS -N test
# send an email when job starts/ends
#PBS -m abe

# Load required modules so that the commands at the computational node are found
module purge
module load binutils/2.26
module load openmpi/1.8.3/gcc
module load gcc/6.1.0
module load R/3.3.0
module load imagemagick

# Change to directory from which job was submitted
cd $PBS_O_WORKDIR

# Run Lotus (mpif90). Note that total np must be the same as stated before. You can also use your /scratch
# directory if the simulation writes too much data for your /home directory.
runLotus np test

# To use an old simulation as the initial conditions for a new one, use
runLotus np new ../old/
